server:
  port: 9080
endpoints:
  shutdown:
    enabled: true
  health:
    sensitive: false
spring:
  application:
    name: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 时间返回格式化
    time-zone: GMT+8
  resources:
    static-locations: classpath:/webapp/template/
    #################### DataSource Start ####################
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.0.0.199:3306/small_video_tool?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/small_video_tool?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    dbcp2:
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池中的最小空闲连接
      min-idle: 10
      max-wait-millis: 60000
    #################### DataSource End ####################

  ######################### freemarker
  freemarker:
    check-template-location: false
  http:
    multipart:
      max-file-size: 100MB #限制默认文件上传大小
      max-request-size: 100MB #限制默认文件上传大小
  mvc:
    favicon:
      enabled: false
  #------------------------ freemarker end
  ######################## redis
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 2000
    pool:
      max-active: 200
      max-wait: 5
      max-idle: 20
      min-idle: 10
#------------------------ redis end

######################### 日志
logging:
  config: classpath:config/logback-spring-dev.xml
  level: debug
#------------------------ 日志end

# 本地参数配置
com:
  mi:
    kaptcha:
      border: 'no'
      border.color: 105,179,90
      textproducer.font.color: 238,238,238
      image.width: 100
      image.height: 38
      textproducer.font.size: 30
      session.key: code
      background.clear.from: 50,50,50
      background.clear.to: 50,50,50
      textproducer.char.length: 4
      textproducer.font.names: Arial
      textproducer.char.string: abcde2345678gfymnpwx
      noise.impl: com.google.code.kaptcha.impl.NoNoise
      obscurificator.impl: com.google.code.kaptcha.impl.Simple

######################## mapper插件
mybatis:
  type-aliases-package: com.huimi.core.mapper
  configuration:
    map-underscore-to-camel-case: true # 数据库开启驼峰转换
mapper:
  mappers:
    - com.huimi.common.baseMapper.QueryMapper
    - com.huimi.common.baseMapper.InsertMapper
    - com.huimi.common.baseMapper.UpdateMapper
    - com.huimi.common.baseMapper.DeleteMapper
  not-empty: false
  identity: MYSQL
  # 枚举转换基本类型
  enum-as-simple-type: true
#----------------------- mapper插件 end
